### PR TITLE
yl556 - Designed GUI layout (close #1)

### LINKED ISSUE #1: Design GUI Layout

### PR DESCRIPTION
**Pull request by Yuhan-Liu-Heidi**

### CODE REVIEW

**Comment by Yuhan-Liu-Heidi** [comment]
GUI layout
The width and height of the area for original/processed images and histograms is still being adjusted.
Please review the layout and tell me if you have any suggestions.

**Comment by chriszhou0916** [comment]
I like the numbering system. Makes it more obvious where to move next, although my eyes moved horizontally from box 1 to box 3 initially and I was still confused. 

Consider when an user selects multiple images or a zip file, and they press start processing. SHould there be a list panel to select which images they want to view? or a drop down menu to select image to preview.

Also, radio buttons to select what image format to download? and a download button? maybe add a preview button too so after they select a new image from the same batch, they can view it

If a user wants to browse past requests, where would the list of past requests show up in the window? then they need to select one of them and click on a button called "view request" to load that request. then they can download, preview, and whatever they want. Should we allow them to select a new processing algorithm and reprocess these images? @Yuhan-Liu-Heidi 

Lastly, we need a button/window for the user to retrieve and view metadata, as discussed in the project plan.

**Comment by Yuhan-Liu-Heidi** [comment]
Thanks for your good advises! @chriszhou0916 

I wanted to make it more compact so I made box 2 under box 1. However, we can definitely work out a better version.

I plan to use popup window for selecting new file/files/zip to upload. If it doesn't work, I might add checkboxes.

But I did forget about the downloading format thing. I'll also add the metadata button. Thanks for bringing them up!

I haven't decided if it is better to use a popup window or not for browsing requests. However, I found some online articles that might help, so it might not be difficult, and I'll give it a try unless proved too hard to implement.

**Comment by NicolasHu11** [comment]
Great job!! Thanks @Yuhan-Liu-Heidi 

1. after entering username, could we have a confirmation whether it's a new user or an existing user? 
if it's a new user, we need to create one. 

2. I'm a bit confused about about this request/action. maybe a button to confirm upload image? Or this is included in the <start processing>? also, after selecting an image, maybe show the filename or show the image?

**Pull request merged**
